# Generated by Django 5.2.5 on 2025-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
